### ISSUE TITLE
Use real stand numbers in the case of SMK XML

### ISSUE THREAD

**Issue by Sorvalampi** [lukefi/metsi-data#1]
Now, it seems, that stands are numbered either sequentially (in rsd) or using stand-id.
In all cases, stand numbering must be done as follows:
stand number = StandNumber.StandNumberExtension (the latter referring to XML variables).

**Comment by jpy-luke** [comment]
I'm going ahead and assume that by stand number you mean identifier. We don't have stand number in the data model, only identifier. This is now set to be the XML Stand id attribute. Will change this to be Stand.StandBasicData.StandNumber with optional extension from Stand.StandBasicData.StandNumberExtension concatenated with a . postfix.

**Comment by Sorvalampi** [comment]
I think identifier is just the variable I mean.
